// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const rawDatabaseUrl = process.env['DATABASE_URL'] ?? '';
const targetSchema = process.env['DB_SCHEMA'] ?? 'dolani_api';

function withSchema(url: string, schema: string): string {
  if (!url) {
    return url;
  }

  try {
    const parsed = new URL(url);
    if (!parsed.searchParams.has('schema')) {
      parsed.searchParams.set('schema', schema);
    }
    return parsed.toString();
  } catch {
    const separator = url.includes('?') ? '&' : '?';
    return `${url}${separator}schema=${encodeURIComponent(schema)}`;
  }
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx ts-node prisma/seed.ts',
  },
  datasource: {
    url: withSchema(rawDatabaseUrl, targetSchema),
  },
});
